marpay/marpay/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

from myuser.views import SignUpAPIView, LogInAPIView, LogOutAPIView


urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    # path('', include('myuser.urls')),
    
    path('admin/', admin.site.urls),

    path('myuser/', include('django.contrib.auth.urls')),
    # path('myuser/', include('myuser.urls')),
    path('api/myuser/', include('myuser.urls', 'api_myuser',)), 

    path('api/sign_up/', SignUpAPIView.as_view(), name='sign_up'),
    path('api/log_in/', LogInAPIView.as_view(), name='log_in'),
    path('api/log_out/', LogOutAPIView.as_view(), name='log_out'),

    # path('medsession/', include('medsession.urls')),
    path('medsession/', include('medsession.urls', 'medsession',)),
    path('api/medsession/', include('medsession.urls', 'api_medsession',)),    
    
    path('api/mytask/', include('mytask.urls', 'api_mytask',)),
] 
# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # removed because nginx is now handling serving files

marpay/myuser/urls.py
from django.urls import path
from django.conf.urls import include, url
from django.views.generic.base import TemplateView
from .views import SignUpView, TestPageView
from . import views

from rest_framework import routers   

app_name = 'myuser' # if not included, it gives error 'Specifying a namespace in include() without providing an app_name '

router = routers.DefaultRouter()
router.register(r'', views.MyUserProfileCRUDAPIView, 'myuser')

# client - > URL -> VIEW (serializer, etc)

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('testpage/', TestPageView.as_view(), name='testpage'), 
    path('profile/', views.MyUserDetailView.as_view(), name='myuser_detail'), 
    path('update/', views.MyUserCustomerDetailsUpdateView.as_view(), name='myuser_update'),     
    path('thw_confirm/', views.RegisterTHWConfirmView.as_view(), name='myuser_register_thw_confirm'), 
    path('physician_confirm/', views.RegisterPhysicianConfirmView.as_view(), name='myuser_register_physician_confirm'),     
    path('get_thw_list/', views.get_thw_list, name='get_thw_list'), # temporary url that automatically adds thw role to customer
    path('get_physician_list/', views.get_physician_list, name='get_physician_list'),   # temporary url that automatically adds physician role to customer    
    path('start_call/', views.start_call, name='start_call'),
    
    #-----------API CALLS-----------------------------------------------------------------------------------------------------------------------------------------------    
           
    path('', include(router.urls)), # TO USE ALL CRUD AT ONCE... The API URLs are now determined automatically by the router. This breaks non-API calls to django
    # # or indiviually 
    # path('', views.MyUserProfileAPIView.as_view(), name='api_list'),
    # path('<int:pk>/', views.MyUserProfileAPIView.as_view(), name='api_details'),
    # path('<int:pk>/update/', views.MyUserProfilePartialUpdateAPIView.as_view(), name='api_update'),
    
]

marpay/templates/base.html
<!-- templates/base.html -->
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Marpay{% endblock %}</title>    
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width,initial-scale=1"> 
	<link rel="shortcut icon" href="#" /> <!-- to take care of favico.ico error -->
	<link href="{% static '/tailwindcssfolder/output.css' %}" rel="stylesheet">
	<link href="{% static '/css_files/home_styles.css' %}" rel="stylesheet">
  <!-- <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet"> -->   
</head>

<body>
  <main>  
  
    {% block intro %}

	{% if user.is_authenticated %}
		<header class="text-gray-700 body-font">
		  <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
		    <nav class="flex lg:w-2/5 flex-wrap items-center text-base md:ml-auto">
		      <a class="mr-5 hover:text-gray-900"href="{% url 'home' %}">Home</a>
		      <a class="mr-5 hover:text-gray-900" href="{% url 'myuser:myuser_detail' %}">Profile</a>
		      <a class="hover:text-gray-900" href="{% url 'logout' %}">Logout</a>
		    </nav>
		    <a class="flex order-first lg:order-none lg:w-1/5 title-font font-medium items-center text-gray-900 lg:items-center lg:justify-center mb-4 md:mb-0">
		      <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-green-500 rounded-full" viewBox="0 0 24 24">
		        <!-- <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path> -->
		        <path d=""></path>
		      </svg>
		      <span class="ml-3 text-xl">marpyx</span>
		    </a>
		    <!-- Right Button
		    <div class="lg:w-2/5 inline-flex lg:justify-end ml-5 lg:ml-0">
		      <button class="inline-flex items-center bg-gray-200 border-0 py-1 px-3 focus:outline-none hover:bg-gray-300 rounded text-base mt-4 md:mt-0">Button
		        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
		          <path d="M5 12h14M12 5l7 7-7 7"></path>
		        </svg>
		      </button>
		    </div> -->
		  </div>
		</header>
		
	{% else %}
		
		<form id="login-form" method="post" role=form action="{% url 'login' %}">
		  {% csrf_token %}  
		  <section class="text-gray-700 body-font">
		  <div class="container px-5 py-24 mx-auto flex flex-wrap items-center">
		    <div class="lg:w-3/5 md:w-1/2 md:pr-16 lg:pr-0 pr-0">
		      <h1 class="title-font font-black text-3xl text-gray-900">marpyx</h1>
		      <!-- <h1 class="title-font font-medium text-3xl text-gray-900">Marpay. Health delivery re-imagined</h1> -->
		      <p class="leading-relaxed mt-4">Health delivery re-imagined</p>
		    </div>
		    <div class="lg:w-2/6 md:w-1/2 bg-gray-200 rounded-lg p-8 flex flex-col md:ml-auto w-full mt-10 md:mt-0">
		      <h2 class="text-gray-900 text-lg font-medium title-font mb-5">Sign In</h2>
		      <input class="bg-white rounded border border-gray-400 focus:outline-none focus:border-green-500 text-base px-4 py-2 mb-4" placeholder="username" type="text" name="username">
		      <input class="bg-white rounded border border-gray-400 focus:outline-none focus:border-green-500 text-base px-4 py-2 mb-4" placeholder="password" type="password" name="password">
		      <button class="text-white bg-green-500 border-0 py-2 px-8 focus:outline-none hover:bg-green-600 rounded text-lg" type="submit">Login</button>
		      <p class="text-lg text-green-500 mt-3 text-right"><a href="{% url 'myuser:signup' %}">Sign Up</a></p>
		    </div>
		  </div>
		</section>
		</form>
		
	{% endif %} 
	
    {% endblock %}
  
    {% block content %}
    {% endblock %}
    
    <script src="{% static 'javascript_files/jquery-3.5.1.min.js' %}"></script>  <!-- JQUERY HERE -->
    <script src="{% static 'javascript_files/twilio-video.min.js' %}"></script>  <!-- TWILIO HERE -->
    <script src="{% static 'javascript_files/require.js' %}"></script>  
    <script src="{% static 'javascript_files/home_functions.js' %}"></script>  
    
  </main>
</body>

</html>

marpay/templates/home.html
<!-- templates/home.html -->
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}

  <section class="text-gray-700 body-font">
  <div class="container mx-auto flex px-5 py-8 md:flex-row flex-col items-center">
    <div class="lg:flex-grow md:w-1/2 lg:pr-24 md:pr-16 flex flex-col md:items-start md:text-left mb-16 md:mb-0 items-center text-center">
      <div class="flex justify-center" id="modal-book">
	    <form method="post" class="get_user_form" action="{% url 'myuser:get_thw_list' %}">	    
			{% csrf_token %}	
	        <button type="submit" class="inline-flex text-white bg-green-500 border-0 py-2 px-6 focus:outline-none hover:bg-green-600 rounded text-lg">THW to Doctor</button>
	    </form>
	    <form>
	    	{% csrf_token %}
        	<button id="call_leave" class="ml-4 inline-flex text-white bg-green-300 border-0 py-2 px-6 focus:outline-none hover:bg-green-400 rounded text-lg">Direct to Doctor</button>
        </form>
      </div>
    </div>
    
     <div class="lg:w-2/3 md:w-1/2 bg-gray-300 rounded-lg overflow-hidden sm:mr-10 p-10 flex items-end justify-start relative">
      <!-- <iframe width="100%" height="100%" class="absolute inset-0" frameborder="0" title="map" marginheight="0" marginwidth="0" scrolling="no" 
      src="https://www.google.com/maps/embed/v1/view?key=AIzaSyDw3UVRUz4etVGcB5sZnL2S3Q7o4hKviBM&center=-33.8569,151.2152" style="filter: grayscale(1) contrast(1.2) opacity(0.4);"></iframe> -->
      <iframe width="100%" height="100%" class="absolute inset-0" frameborder="0" title="map" marginheight="0" marginwidth="0" scrolling="no" 
      src="https://maps.google.com/maps?width=100%&amp;height=600&amp;hl=en&amp;q=%C4%B0zmir+(My%20Business%20Name)&amp;ie=UTF8&amp;t=&amp;z=14&amp;iwloc=B&amp;output=embed" style="filter: grayscale(1) contrast(1.2) opacity(0.4);">
      </iframe>
      
      <iframe width="100%" height="100%" class="absolute inset-0" frameborder="0" title="map" marginheight="0" marginwidth="0" scrolling="no" 
      style="filter: grayscale(1) contrast(1.2) opacity(0.4);">
      </iframe>
      
      <div class="bg-white items-center relative flex flex-col w-full py-6">
      
        <p id="count"></p>
        <div id="container_vid" class="container_vid lg:w-1/2 px-6 mt-4 lg:mt-0">        
            <div id="local" class="participant"><div></div><div>Me</div></div> 
        	<hr>
        </div>
               
        
        <div class="lg:w-1/2 px-6">
          <h2 class="title-font font-medium text-gray-900 tracking-widest text-3xl">Hi, <div id="call_name" class="inline-flex">{{ user.first_name }}</div></h2>
          <span class="text-center bg-warning text-sm">Available THWs in your area</span>
		  <!--<p class="leading-relaxed">... at your service today</p> -->
        </div>
        <div class="lg:w-1/2 px-6 mt-4 lg:mt-0">           
        	{% include 'myuser/myuser_thw_list.html' %} 
        </div>
      </div>
           
      
    </div>    
      
  </div>
</section>  
   
{% else %}
  
{% endif %}
{% endblock %}

marpay/templates/signup.html
{% extends 'base.html' %}
 
{% block intro %}
{% endblock %}

{% block content %}

	<form method="post">
	  {% csrf_token %}	  
	  <section class="text-gray-700 body-font">
		  <div class="container px-5 py-8 flex flex-wrap items-center">		  
			<div class="max-w-screen-sm bg-gray-200 rounded-lg p-8 flex flex-col md:ml-auto w-full mt-10 md:mt-0">
			
			  {% for field in form %}
			    <p>
			      {{ field.label_tag }}<br>
			      {{ field }}
			      {% if field.help_text %}
			        <small style="color: grey">{{ field.help_text }}</small>
			      {% endif %}
			      {% for error in field.errors %}
			        <p style="color: red">{{ error }}</p>
			      {% endfor %}
			    </p><br>
			  {% endfor %}
		  	  <button class="text-white bg-green-500 border-0 py-2 px-8 focus:outline-none hover:bg-green-600 rounded text-lg" type="submit">Sign up to Marpay</button>
		      <p class="text-lg text-green-500 mt-3 text-right"><a href="{% url 'home' %}">Back to Login</a></p>
			</div>
		  </div>
	  </section>
	</form>
  
  
{% endblock %}

marpay/templates/testpage.html
<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">

  <title>TestPage</title>
  <meta name="description" content="The HTML5 Herald">
  <meta name="author" content="SitePoint">

  <link rel="stylesheet" href="css/styles.css?v=1.0">

</head>

<head>
	<meta charset="utf-8">
	<link rel="icon" href="/tailblocks/favicon.png">
	<meta name="viewport" content="width=device-width,initial-scale=1">
	<meta name="theme-color" content="#000000">
	<meta name="description" content="Web site created using create-react-app">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/1.4.6/tailwind.min.css">
	<link rel="manifest" href="/tailblocks/manifest.json">
	<title>tailblocks — Ready-to-use Tailwind CSS blocks</title>
	<link href="/tailblocks/static/css/main.e64c1c7e.chunk.css" rel="stylesheet">
</head>

<body>

<section class="text-gray-700 body-font relative">
  <div class="container px-5 py-24 mx-auto flex sm:flex-no-wrap flex-wrap">
    <div class="lg:w-2/3 md:w-1/2 bg-gray-300 rounded-lg overflow-hidden sm:mr-10 p-10 flex items-end justify-start relative">
      <iframe width="100%" height="100%" class="absolute inset-0" frameborder="0" title="map" marginheight="0" marginwidth="0" scrolling="no" src="https://maps.google.com/maps?width=100%&height=600&hl=en&q=%C4%B0zmir+(My%20Business%20Name)&ie=UTF8&t=&z=14&iwloc=B&output=embed" style="filter: grayscale(1) contrast(1.2) opacity(0.4);"></iframe>
      <div class="bg-white relative flex flex-wrap py-6">
        <div class="lg:w-1/2 px-6">
          <h2 class="title-font font-medium text-gray-900 tracking-widest text-sm">ADDRESS</h2>
          <p class="leading-relaxed">Photo booth tattooed prism, portland taiyaki hoodie neutra typewriter</p>
        </div>
        <div class="lg:w-1/2 px-6 mt-4 lg:mt-0">
          <h2 class="title-font font-medium text-gray-900 tracking-widest text-sm">EMAIL</h2>
          <a class="text-indigo-500 leading-relaxed">example@email.com</a>
          <h2 class="title-font font-medium text-gray-900 tracking-widest text-sm mt-4">PHONE</h2>
          <p class="leading-relaxed">123-456-7890</p>
        </div>
      </div>
    </div>
    <div class="lg:w-1/3 md:w-1/2 bg-white flex flex-col md:ml-auto w-full md:py-8 mt-8 md:mt-0">
      <h2 class="text-gray-900 text-lg mb-1 font-medium title-font">Feedback</h2>
      <p class="leading-relaxed mb-5 text-gray-600">Post-ironic portland shabby chic echo park, banjo fashion axe</p>
      <input class="bg-white rounded border border-gray-400 focus:outline-none focus:border-indigo-500 text-base px-4 py-2 mb-4" placeholder="Name" type="text">
      <input class="bg-white rounded border border-gray-400 focus:outline-none focus:border-indigo-500 text-base px-4 py-2 mb-4" placeholder="Email" type="email">
      <textarea class="bg-white rounded border border-gray-400 focus:outline-none h-32 focus:border-indigo-500 text-base px-4 py-2 mb-4 resize-none" placeholder="Message"></textarea>
      <button class="text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">Button</button>
      <p class="text-xs text-gray-500 mt-3">Chicharrones blog helvetica normcore iceland tousled brook viral artisan.</p>
    </div>
  </div>
</section>


</body>
</html>