marpay/myuser/urls.py
from django.urls import path
from django.conf.urls import include, url
from django.views.generic.base import TemplateView
from .views import SignUpView, TestPageView
from . import views

from rest_framework import routers   

app_name = 'myuser' # if not included, it gives error 'Specifying a namespace in include() without providing an app_name '

router = routers.DefaultRouter()
router.register(r'', views.MyUserProfileCRUDAPIView, 'myuser')

# client - > URL -> VIEW (serializer, etc)

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('testpage/', TestPageView.as_view(), name='testpage'), 
    path('profile/', views.MyUserDetailView.as_view(), name='myuser_detail'), 
    path('update/', views.MyUserCustomerDetailsUpdateView.as_view(), name='myuser_update'),     
    path('thw_confirm/', views.RegisterTHWConfirmView.as_view(), name='myuser_register_thw_confirm'), 
    path('physician_confirm/', views.RegisterPhysicianConfirmView.as_view(), name='myuser_register_physician_confirm'),     
    path('get_thw_list/', views.get_thw_list, name='get_thw_list'), # temporary url that automatically adds thw role to customer
    path('get_physician_list/', views.get_physician_list, name='get_physician_list'),   # temporary url that automatically adds physician role to customer    
    path('start_call/', views.start_call, name='start_call'),
    
    #-----------API CALLS-----------------------------------------------------------------------------------------------------------------------------------------------    
           
    path('', include(router.urls)), # TO USE ALL CRUD AT ONCE... The API URLs are now determined automatically by the router. This breaks non-API calls to django
    # # or indiviually 
    # path('', views.MyUserProfileAPIView.as_view(), name='api_list'),
    # path('<int:pk>/', views.MyUserProfileAPIView.as_view(), name='api_details'),
    # path('<int:pk>/update/', views.MyUserProfilePartialUpdateAPIView.as_view(), name='api_update'),
    
]

marpay/myuser/templates/myuser/myuser_detail.html
<!-- templates/home.html -->
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}


<section class="text-gray-700 body-font overflow-hidden">
  <div class="container px-5 py-8 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">PROFILE</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ user.username }}</h1>
        <div class="flex mb-4">
          <a class="flex-grow text-gray-900 py-2 text-lg px-1">Details</a>
        </div><div class="flex border-t border-gray-300 py-2">
          <span class="text-gray-500">Name</span>
          <span class="ml-auto text-gray-900">{{ user.first_name }} {{ user.last_name }}</span>
        </div>
        <div class="flex border-t border-b mb-6 border-gray-300 py-2">
          <span class="text-gray-500">Email</span>
          <span class="ml-auto text-gray-900">{{ user.email }}</span>
        </div>
        <div class="flex flex-row-reverse justify-center">
          <a class="text-lg text-green-500 hover:text-green-700 text-center lex cursor-pointer" onclick="revealMoreButtons()">More...</a>
          <a class="text-lg text-center lex">&nbsp;&nbsp;|&nbsp;&nbsp;</a>
          <a class="text-lg text-green-500 hover:text-green-700 text-center lex" href="{% url 'myuser:myuser_update' %}">Edit Profile</a>
          <a class="text-lg text-center lex">&nbsp;&nbsp;|&nbsp;&nbsp;</a>
          <a class="text-lg text-green-500 hover:text-green-700 text-center lex" href="{% url 'myuser:myuser_detail' %}">Medical History</a>  
        </div>
        <div class="flex flex-row-reverse">
			<div id="div_more_buttons" class='hidden'>
			
		      <form method="POST">
			  {% csrf_token %}			
			  <a class="text-sm text-green-500 hover:text-green-700 lex m-2" href="{% url 'myuser:myuser_register_thw_confirm' %}">			  
				{% if is_thw %} De-register as THW {% else %} Register as THW {% endif %}
			  </a>			  			
			  <a class="text-sm text-green-500 hover:text-green-700 lex m-2" href="{% url 'myuser:myuser_register_physician_confirm' %}">			  
				{% if is_physician %} De-register as Physician {% else %} Register as Physician {% endif %}
			  </a>
			  </form>
			  
			</div>
        </div>        
      </div>
      <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
    </div>
  </div>
</section> 

<script>
	function revealMoreButtons() {
	  var x = document.getElementById("div_more_buttons");
	  if (x.style.display === "block") {
	    x.style.display = "none";
	  } else {
	    x.style.display = "block";
	  }
	}
</script>

{% endif %}
{% endblock %}

marpay/myuser/templates/myuser/myuser_register_physician_confirm.html
<!-- templates/home.html -->
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}

 <section class="text-gray-700 body-font">
  <div class="container px-5 py-8 flex flex-wrap items-center">		  
	<div class="max-w-screen-sm bg-gray-200 rounded-lg p-8 flex flex-col md:ml-auto w-full mt-10 md:mt-0">
		 
        <div class="max-w-screen-sm bg-gray-200 rounded-lg p-8 flex flex-col md:ml-auto w-full mt-10 md:mt-0">        
        <div class="border-t border-b mb-6 border-gray-300 py-2 text-sm text-center">   	
				{% if is_physician %} After approval... Successfully registered as a Physician  
				{% else %} Successfully de-registered as a Physician 
				{% endif %}
         </div>
        <div class="border-t border-b mb-6 border-gray-300 py-2 text-center">
          	<a class="text-lg text-green-500 hover:text-green-700 lex m-2" href="{% url 'myuser:myuser_detail' %}">Back to Profile</a> 
         </div> 
        </div>
	    
	</div>
  </div>
 </section>

{% endif %}
{% endblock %}

marpay/myuser/templates/myuser/myuser_register_thw_confirm.html
<!-- templates/home.html -->
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}

 <section class="text-gray-700 body-font">
  <div class="container px-5 py-8 flex flex-wrap items-center">		  
	<div class="max-w-screen-sm bg-gray-200 rounded-lg p-8 flex flex-col md:ml-auto w-full mt-10 md:mt-0">
		 
        <div class="max-w-screen-sm bg-gray-200 rounded-lg p-8 flex flex-col md:ml-auto w-full mt-10 md:mt-0">        
        <div class="border-t border-b mb-6 border-gray-300 py-2 text-sm text-center">      	
				{% if is_thw %} After approval... Successfully registered as a Telemedical Health Worker  
				{% else %} Successfully de-registered as a Telemedical Health Worker
				{% endif %}   
         </div>
        <div class="border-t border-b mb-6 border-gray-300 py-2 text-center">
          	<a class="text-lg text-green-500 hover:text-green-700 lex m-2" href="{% url 'myuser:myuser_detail' %}">Back to Profile</a> 
         </div> 
        </div>
	    
	</div>
  </div>
 </section>

{% endif %}
{% endblock %}

marpay/myuser/templates/myuser/myuser_thw_list.html
<table class="table" id="user-table">
    <!-- <thead>
      <tr>
        <th>#</th>
        <th>Name</th>
      </tr>
    </thead> -->
    <tbody>    
    {% for user in user_thw_list %}
	  <tr>	  
        <div class="flex border-t border-gray-300 py-2">
          <span class="ml-auto text-gray-900 m-2 text-left">{{ user.first_name }} {{ user.last_name }}</span>
          <span class="text-lg text-green-500 hover:text-green-700 m-2 text-center" href="">Hail</span>
        </div>
	  <tr></tr>
	{% empty %}
	  <tr>
	    <td colspan="7" class="text-center bg-warning">No Available THW</td>
	  </tr>
	{% endfor %}  
    
	  			
    </tbody>
 </table>

marpay/myuser/templates/myuser/myuser_update.html
<!-- templates/home.html -->
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
	
    
 <section class="text-gray-700 body-font">
  <div class="container px-5 py-8 flex flex-wrap items-center">		  
	<div class="max-w-screen-sm bg-gray-200 rounded-lg p-8 flex flex-col md:ml-auto w-full mt-10 md:mt-0">
		    
	    <form method="POST">
		{% csrf_token %}	
		     <h2>User Information:</h2>
		     <!-- Make use of Django's automatic form templating -->
		     {{ myuser_update_form.as_p }}
		
		     <!-- Now add the sub-form to this form -->
		     <h3>More Details:</h3>
		     {{ customer_details_update_form.as_p }}
		     <p><button class="text-white bg-green-500 border-0 py-2 px-8 focus:outline-none hover:bg-green-600 rounded text-lg" type="submit">Update</button></p>
		</form>
	    
	    
	</div>
  </div>
 </section>


{% endif %}
{% endblock %}